trigger:
  - master

jobs:
  - job: Linux Build
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: UseGoVersion@0
          displayName: 'Use Go 1.12'
          inputs:
            versionSpec: '1.12'

      - task: Go@0
        inputs:
          command: 'build'
          #customCommand: # Required when command == Custom
          arguments: '-o azcopy_linux'
          workingDirectory:

#  - job: MacOS Build
#    pool:
#      vmImage: 'xcode9-macos10.13'
#    steps:
#      - bash: ./build.sh
#        env:
#          COREHOST_TRACE: 0
#          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
#          DOTNET_CLI_TELEMETRY_OPTOUT: 1
#
#  - job: Windows Build
#    pool:
#      vmImage: 'vs2017-win2016'
#    steps:
#      - powershell: .\build.ps1
#        env:
#          COREHOST_TRACE: 0
#          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
#          DOTNET_CLI_TELEMETRY_OPTOUT: 1